/**
 * BM25 ranking over a prebuilt OpenStax section index.
 *
 * Pure scoring: no DOM, no fetch, no imports.  Everything this needs arrives as
 * plain data, which is what lets it run under `node --test` with no jsdom and no
 * network -- the same contract src/qti_export.js follows.
 *
 * Why BM25 and not embeddings
 * ---------------------------
 * The corpus is a handful of textbooks with a human-authored index: every
 * section already ships a title, learning objectives, key terms and an
 * author-written summary.  Ranking that is a linear scan over a few hundred
 * records, which finishes in well under a millisecond.  Embeddings would buy
 * fuzzy matching we do not need (the query is written by an LLM that shares the
 * book's vocabulary) and cost a build-time embedding pass, a query-embedding
 * call on every turn against a 256 MB auto-stopping server, and a failure mode
 * that is silent -- a stale vector index degrades into slightly-wrong sections
 * that nobody notices, where a stale section id 404s loudly.
 *
 * If recall ever does prove insufficient, scoring sits behind rankSections() on
 * purpose: add an injected `opts.embedder`, ship quantised vectors as a purely
 * additive build artefact, and fuse with reciprocal-rank fusion.  Nothing about
 * the index shape or the two-stage fetch has to change.
 *
 * Term and document frequencies are computed by
 * scripts/build_textbook_corpus.py, not here.  The browser only ever tokenises
 * the *query*, so the Python/JS parity surface is one short string rather than
 * five megabytes of prose.  tokenize() below MUST stay in sync with
 * build_textbook_corpus.py:tokenize(); src/textbook_index.test.js pins that
 * against a fixture generated by the Python side.
 */

const STOPWORDS = new Set(
  ("a an and are as at be been but by can for from had has have how in into is it its " +
   "may more most not of on or that the their them then there these they this to was " +
   "were what when where which who will with would you your").split(" ")
);

const TOKEN_RE = /[a-z0-9]+/g;

/** Lowercase, split on non-alphanumerics, drop stopwords and short tokens. */
export function tokenize(text) {
  const out = [];
  const lowered = String(text == null ? "" : text).toLowerCase();
  for (const match of lowered.matchAll(TOKEN_RE)) {
    let tok = match[0];
    if (tok.length < 3 || STOPWORDS.has(tok)) continue;
    // Conservative plural strip.  Linguistic correctness matters far less than
    // both sides doing exactly the same thing.
    if (tok.length > 3 && tok.endsWith("s") && !/(?:ss|us|is)$/.test(tok)) {
      tok = tok.slice(0, -1);
    }
    if (tok.length >= 3) out.push(tok);
  }
  return out;
}

/**
 * Pool df/docCount/avgLen across several book indexes.
 *
 * Inverse document frequency is meaningless across books unless the statistics
 * come from one pool.  "integration" appears in 17 of Calculus Volume 2's 50
 * sections but is rare in University Physics, so scoring each book against its
 * own df handed a physics section that mentions integration once a far larger
 * idf than Calculus' section actually *titled* "Integration by Parts" -- and it
 * won.  Merging is cheap (a few thousand terms per book) and has to happen at
 * query time, because which books are enabled is a per-question-set choice.
 */
export function combineStats(indexes) {
  const df = Object.create(null);
  let docCount = 0;
  let weighted = 0;
  for (const index of indexes) {
    if (!index) continue;
    docCount += index.docCount || 0;
    weighted += (index.avgLen || 0) * (index.docCount || 0);
    for (const [term, n] of Object.entries(index.df || {})) {
      df[term] = (df[term] || 0) + n;
    }
  }
  return { df, docCount, avgLen: docCount ? weighted / docCount : 1 };
}

/** Okapi BM25 inverse document frequency. */
function idf(df, docCount) {
  return Math.log(1 + (docCount - df + 0.5) / (df + 0.5));
}

/**
 * Score every section in `index` against pre-tokenized query terms.
 * Returns [{ id, score }] for sections that matched at least one term.
 */
export function scoreBM25(queryTerms, index, opts = {}) {
  const { k1 = 1.2, b = 0.75, stats = null } = opts;
  const { sections = [] } = index;
  // `stats` lets the caller score every book against one pooled df/avgLen.
  const { df = {}, docCount = 0, avgLen = 1 } = stats || index;
  if (!queryTerms.length || !docCount) return [];

  // A repeated query term should count twice, so fold duplicates into a weight.
  const weights = new Map();
  for (const term of queryTerms) weights.set(term, (weights.get(term) || 0) + 1);

  const scored = [];
  for (const section of sections) {
    const tf = section.tf || {};
    const norm = k1 * (1 - b + (b * (section.len || 0)) / (avgLen || 1));
    let score = 0;
    let matched = 0;
    for (const [term, weight] of weights) {
      const f = tf[term];
      if (!f) continue;
      matched += 1;
      score += weight * idf(df[term] || 0, docCount) * ((f * (k1 + 1)) / (f + norm));
    }
    if (score > 0) {
      scored.push({ id: section.id, score, coverage: matched / weights.size, section });
    }
  }
  return scored;
}

/**
 * Combine BM25 with how much of the query a section actually covers.
 *
 * Raw BM25 rewards a section that mentions one query term very often as much as
 * one that mentions every term.  Across several books that is actively harmful:
 * "chain rule derivative composite function" scored College Physics' *Fission*
 * section highly on "chain" (chain reaction) and "function", ranking it above
 * Calculus' actual "The Chain Rule".  Squaring coverage pushes partial lexical
 * coincidences down hard while leaving genuine matches almost untouched.
 */
export function relevance(hit) {
  return hit.score * hit.coverage * hit.coverage;
}

/** Numeric-aware compare for section numbers like "4.3" vs "4.10". */
function compareNumbers(a, b) {
  const pa = String(a).split(".").map(Number);
  const pb = String(b).split(".").map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] || 0) - (pb[i] || 0);
    if (d) return d;
  }
  return 0;
}

/**
 * Rank sections of one book.
 *
 * `chapters` and `sections` are independent filters and both may apply at
 * once: `chapters` is the chapter-number pin a model may pass in a single
 * tool call, `sections` is the section-id allow-list an instructor pinned for
 * this book ahead of time (from the textbook-grounding tree). Either, both or
 * neither may be set.
 *
 * `minScore` is a floor, not a formality: returning the three least-bad
 * sections for a query the book does not cover is worse than returning nothing,
 * because the model treats whatever it is handed as evidence.  The caller falls
 * back to the chapter catalog when this comes back empty.
 */
export function rankSections(query, index, opts = {}) {
  const { topK = 5, chapters = null, sections = null, minScore = 2.0 } = opts;
  const terms = tokenize(query);
  let scored = scoreBM25(terms, index, opts);

  if (chapters && chapters.length) {
    const wanted = new Set(chapters.map(Number));
    scored = scored.filter((s) => wanted.has(Number(s.section.ch)));
  }
  if (sections && sections.length) {
    const wanted = new Set(sections);
    scored = scored.filter((s) => wanted.has(s.id));
  }

  scored = scored
    .map((s) => ({ ...s, relevance: relevance(s) }))
    .filter((s) => s.relevance >= minScore);

  scored.sort((x, y) => (y.relevance - x.relevance) || compareNumbers(x.id, y.id));
  return scored.slice(0, topK);
}
