import test from "node:test";
import assert from "node:assert/strict";
import {
  tokenize,
  scoreBM25,
  relevance,
  rankSections,
  combineStats,
} from "./textbook_index.js";

/**
 * Generated by scripts/build_textbook_corpus.py:tokenize().  This is the whole
 * Python/JS parity surface: term and document frequencies are computed by the
 * build, so the browser only ever tokenizes a query.  If this test fails, the
 * two tokenizers have drifted and every stored tf key is suspect.
 *
 * Regenerate with:
 *   python3 -c "import sys;sys.path.insert(0,'scripts');\
 *   from build_textbook_corpus import tokenize;print(tokenize('...'))"
 */
const PYTHON_TOKENIZER_FIXTURE = [
  ["Newton's Second Law of Motion", ["newton", "second", "law", "motion"]],
  ["coefficient of kinetic friction on an inclined plane",
    ["coefficient", "kinetic", "friction", "inclined", "plane"]],
  ["RIEMANN sums, 3-D vectors", ["riemann", "sum", "vector"]],
  ["physics buses gases axis focus radius",
    ["physic", "buse", "gase", "axis", "focus", "radius"]],
  ["the of and a an is it to", []],
  ["", []],
  ["Ohm law: V=IR (12.5 volts)", ["ohm", "law", "volt"]],
  ["Uniform Circular Motion & Gravitation",
    ["uniform", "circular", "motion", "gravitation"]],
];

test("tokenize matches the Python build tokenizer exactly", () => {
  for (const [input, expected] of PYTHON_TOKENIZER_FIXTURE) {
    assert.deepEqual(tokenize(input), expected, `tokenize(${JSON.stringify(input)})`);
  }
});

test("tokenize tolerates null and undefined rather than throwing", () => {
  assert.deepEqual(tokenize(null), []);
  assert.deepEqual(tokenize(undefined), []);
});

// A tiny three-section book.  "friction" is rare (1 doc), "motion" is common
// (3 docs), which is what makes the IDF assertion below meaningful.
function fixtureIndex() {
  return {
    docCount: 3,
    avgLen: 100,
    df: { friction: 1, motion: 3, force: 2, energy: 1 },
    sections: [
      { id: "1.1", sh: "ch01", ch: 1, t: "Motion", len: 100, tf: { motion: 30, force: 5 } },
      { id: "1.2", sh: "ch01", ch: 1, t: "Friction", len: 100, tf: { friction: 30, motion: 5, force: 5 } },
      { id: "2.1", sh: "ch02", ch: 2, t: "Energy", len: 100, tf: { energy: 30, motion: 5 } },
    ],
  };
}

test("scoreBM25 ranks a rare term above a common one", () => {
  const index = fixtureIndex();
  const rare = scoreBM25(tokenize("friction"), index).find((h) => h.id === "1.2");
  const common = scoreBM25(tokenize("motion"), index).find((h) => h.id === "1.1");
  // Equal term frequency (30) in equal-length docs, so only IDF separates them.
  assert.ok(rare.score > common.score,
    `rare term should outscore common: ${rare.score} vs ${common.score}`);
});

test("scoreBM25 reports the fraction of distinct query terms a section matched", () => {
  const index = fixtureIndex();
  const hits = scoreBM25(tokenize("friction motion"), index);
  assert.equal(hits.find((h) => h.id === "1.2").coverage, 1);
  assert.equal(hits.find((h) => h.id === "1.1").coverage, 0.5);
});

test("scoreBM25 returns nothing for an empty query or an empty index", () => {
  assert.deepEqual(scoreBM25([], fixtureIndex()), []);
  assert.deepEqual(scoreBM25(tokenize("friction"), { docCount: 0, sections: [] }), []);
});

test("relevance penalises partial coverage quadratically", () => {
  // The defect this guards: a section matching one query term very often used to
  // outrank a section matching every term, so "chain rule derivative composite
  // function" returned College Physics' Fission section (chain reaction) above
  // Calculus' The Chain Rule.
  const full = relevance({ score: 10, coverage: 1 });
  const half = relevance({ score: 10, coverage: 0.5 });
  assert.equal(full, 10);
  assert.equal(half, 2.5);
  assert.ok(relevance({ score: 18, coverage: 0.5 }) < full,
    "a much higher raw score at half coverage must still lose to full coverage");
});

test("rankSections filters to the requested chapters", () => {
  const hits = rankSections("motion", fixtureIndex(), { chapters: [2], minScore: 0 });
  assert.deepEqual(hits.map((h) => h.id), ["2.1"]);
});

test("rankSections drops everything below the score floor", () => {
  // Returning the least-bad sections for an uncovered topic is worse than
  // returning none: the model treats whatever it is handed as evidence.
  assert.deepEqual(rankSections("motion", fixtureIndex(), { minScore: 1e6 }), []);
  assert.deepEqual(rankSections("thermodynamics entropy", fixtureIndex()), []);
});

test("rankSections honours topK", () => {
  assert.equal(rankSections("motion", fixtureIndex(), { topK: 2, minScore: 0 }).length, 2);
});

test("rankSections breaks ties by section number, not by array order", () => {
  const index = {
    docCount: 2, avgLen: 100, df: { motion: 2 },
    sections: [
      { id: "1.10", sh: "ch01", ch: 1, len: 100, tf: { motion: 10 } },
      { id: "1.2", sh: "ch01", ch: 1, len: 100, tf: { motion: 10 } },
    ],
  };
  // Identical scores, so ordering must come from the numeric compare: 1.2 < 1.10.
  assert.deepEqual(rankSections("motion", index, { minScore: 0 }).map((h) => h.id),
    ["1.2", "1.10"]);
});

test("combineStats pools document frequencies across books", () => {
  const a = { docCount: 50, avgLen: 100, df: { integration: 17, force: 1 } };
  const b = { docCount: 150, avgLen: 200, df: { integration: 2, force: 40 } };
  const stats = combineStats([a, b]);
  assert.equal(stats.docCount, 200);
  assert.equal(stats.df.integration, 19);
  assert.equal(stats.df.force, 41);
  // Weighted by document count, not a plain mean of the two averages.
  assert.equal(stats.avgLen, (100 * 50 + 200 * 150) / 200);
});

test("combineStats ignores missing indexes", () => {
  assert.equal(combineStats([null, undefined]).docCount, 0);
});

test("pooled statistics let the right book win a shared term", () => {
  // The regression: scored against its own df, a physics section that mentions
  // "integration" once beat Calculus' section titled "Integration by Parts",
  // because the term is rare in physics and common in calculus.
  const calculus = {
    docCount: 50, avgLen: 100, df: { integration: 17, part: 10 },
    sections: [{ id: "3.1", sh: "ch03", ch: 3, len: 100, tf: { integration: 26, part: 23 } }],
  };
  const physics = {
    docCount: 150, avgLen: 100, df: { integration: 1, part: 60 },
    sections: [{ id: "9.1", sh: "ch09", ch: 9, len: 100, tf: { integration: 3, part: 8 } }],
  };

  const own = [
    rankSections("integration by parts", calculus, { minScore: 0 })[0].relevance,
    rankSections("integration by parts", physics, { minScore: 0 })[0].relevance,
  ];
  assert.ok(own[1] > own[0], "precondition: per-book stats give the physics section the edge");

  const stats = combineStats([calculus, physics]);
  const pooled = [
    rankSections("integration by parts", calculus, { minScore: 0, stats })[0].relevance,
    rankSections("integration by parts", physics, { minScore: 0, stats })[0].relevance,
  ];
  assert.ok(pooled[0] > pooled[1], "pooled stats must put Integration by Parts first");
});
